export const CAREER_OPTIONS = [
  "Family Services Specialist 1 (Nevada State)",
  "Social Services Caseworker",
  "Certified Nursing Assistant (CNA)",
  "Medical Assistant",
  "Patient Care Technician (PCT)",
  "Pharmacy Technician",
  "Medical Billing & Coding (CPC / CCS)",
  "Phlebotomy Technician (CPT / NHA)",
  "Dental Assistant (RDA / CDA)",
  "Licensed Practical Nurse (LPN / LVN)",
  "Registered Nurse (NCLEX-RN)",
  "Surgical Technologist (CST)",
  "Veterinary Technician",
  "Police Officer",
  "Firefighter / EMT",
  "Postal Worker",
  "Administrative / Office Assistant",
  "Bookkeeper / Accounting Clerk",
  "Bank Teller",
  "Paralegal / Legal Assistant",
  "Human Resources (SHRM-CP / PHR)",
  "Insurance Agent",
  "Electrician (Apprentice / Journeyman)",
  "Plumber (Apprentice / Journeyman)",
  "Welder (Certified Welder)",
  "Auto Mechanic (ASE)",
  "HVAC Technician",
  "Commercial Driver (CDL)",
  "Software Developer / Coding",
  "Data Analyst",
  "Information Technology",
  "IT Support / CompTIA A+",
  "Cybersecurity Analyst (Security+)",
  "Cloud Computing (AWS / Azure)",
  "Project Management (PMP / CAPM)",
  "Real Estate Agent",
  "Cosmetology License",
  "Teacher Certification (Praxis)",
  "Teaching Assistant / Paraprofessional",
  "Childcare Provider (CDA)",
] as const;
