export const CAREER_OPTIONS = [
  "Family Service Specialist 1",
  "Social Services Caseworker",
  "Certified Nursing Assistant (CNA)",
  "Medical Assistant",
  "Pharmacy Technician",
  "Police Officer",
  "Firefighter / EMT",
  "Postal Worker",
  "Administrative / Office Assistant",
  "Bookkeeper / Accounting Clerk",
  "Bank Teller",
  "Electrician (Apprentice / Journeyman)",
  "HVAC Technician",
  "Commercial Driver (CDL)",
  "IT Support / CompTIA A+",
  "Project Management (PMP / CAPM)",
  "Real Estate Agent",
  "Cosmetology License",
  "Teacher Certification (Praxis)",
] as const;
