import type { BuiltInGame } from "./types";

export const BUILT_IN_GAMES: BuiltInGame[] = [
  {
    id: "education-skills-lab",
    title: "School Skills Lab",
    description:
      "Hands-on games for every grade — kindergarten through grade 12, plus college and trade school. Letters, math, writing, science, algebra, research skills, and more.",
    subjects: ["mixed", "math", "science", "vocabulary", "careers", "logic"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "3–10 min each",
    skills: ["Grade-level skills", "School readiness", "Academic practice"],
    depth: "featured",
    hook: "K–12 + college + trade",
  },
  {
    id: "career-skills-lab",
    title: "Career Skills Lab",
    description:
      "Hands-on skill games for every career we support — type like an office pro, code like IT support, wire like an electrician, calculate like pharmacy tech, build PCs, and more.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "3–12 min each",
    skills: ["Job-ready skills", "Career practice", "Certification prep"],
    depth: "featured",
    hook: "19 careers · real skills",
  },
  {
    id: "career-match-party",
    title: "Career Match Party",
    description:
      "Visit six themed rooms and pick activities you would enjoy. Discover your Holland RIASEC interest profile and matching careers.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "8–12 min",
    skills: ["Self-awareness", "Career exploration", "Interest mapping"],
    depth: "featured",
    hook: "Find your career personality",
  },
  {
    id: "skills-missions",
    title: "Skills Mission Board",
    description:
      "Complete real-world mission scenarios in healthcare, technology, skilled trades, or business. Learn how pros think under pressure.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "10–15 min",
    skills: ["Workplace judgment", "Professional skills", "Decision-making"],
    depth: "featured",
    hook: "Job missions that teach",
  },
  {
    id: "future-path-finder",
    title: "Future Path Finder",
    description:
      "Answer preference questions about school, work style, and goals. Get your top three career pathways with study suggestions.",
    subjects: ["careers"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "6–10 min",
    skills: ["Career planning", "Self-reflection", "Goal setting"],
    depth: "featured",
    hook: "Match interests to futures",
  },
  {
    id: "boss-battle",
    title: "Knowledge Boss Battle",
    description:
      "Defeat three bosses by answering questions. Combo streaks deal bonus damage. HP bars, battles, and victories — study feels like a video game.",
    subjects: ["mixed", "science", "math", "vocabulary"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "8–15 min",
    skills: ["Recall under pressure", "Multi-subject review", "Motivation"],
    depth: "featured",
    hook: "Fight bosses with your brain",
  },
  {
    id: "career-quest",
    title: "Career Life Quest",
    description:
      "A branching life story from high school to your first big opportunity. Every choice shapes your path toward a future career.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "10–15 min",
    skills: ["Career exploration", "Decision-making", "Self-reflection"],
    depth: "featured",
    hook: "Your choices shape your future",
  },
  {
    id: "day-on-the-job",
    title: "Day One on the Job",
    description:
      "Simulate a real first day as a nurse, developer, teacher, or electrician. Make professional decisions and see how ready you are.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "8–12 min",
    skills: ["Workplace judgment", "Professional skills", "Career realism"],
    depth: "featured",
    hook: "Test-drive a real job",
  },
  {
    id: "lab-escape",
    title: "Lab Escape",
    description:
      "Locked in after hours! Solve science puzzles room by room to collect clues and escape. Escape-room tension meets classroom content.",
    subjects: ["science"],
    ages: ["kids", "teens", "all"],
    duration: "10–12 min",
    skills: ["Science reasoning", "Problem-solving", "Safety awareness"],
    depth: "featured",
    hook: "Escape the science lab",
  },
  {
    id: "jeopardy-arena",
    title: "Jeopardy Arena",
    description:
      "Game-show board across Space, Careers, Math, and Kids Science. Pick dollar values, risk wrong answers, and chase a high score.",
    subjects: ["mixed", "science", "math", "careers"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "10–15 min",
    skills: ["Quick recall", "Strategy", "Friendly competition"],
    depth: "featured",
    hook: "Game show energy",
  },
  {
    id: "quiz-show",
    title: "Quiz Show",
    description:
      "Ten questions, fifteen seconds each. Faster correct answers earn more points. Beat your personal best — game-show energy without leaving LearnForge.",
    subjects: ["mixed", "math", "science", "careers", "geography"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "3–5 min",
    skills: ["Speed", "Recall", "Active learning"],
    depth: "quick",
    hook: "Kahoot-style solo",
  },
  {
    id: "survival-run",
    title: "Survival Run",
    description:
      "Three lives, twelve questions. Wrong answers cost a heart — arcade-style review with explanations after every round.",
    subjects: ["mixed", "math", "science", "careers", "geography"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "4–6 min",
    skills: ["Recall", "Resilience", "Learning from mistakes"],
    depth: "quick",
    hook: "3 lives arcade quiz",
  },
  {
    id: "career-cash",
    title: "Career Cash",
    description:
      "Earn coins on career and workplace questions. Spend on a 50/50 power-up — strategy layered on top of real career content.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "5–8 min",
    skills: ["Career knowledge", "Decision-making", "Workplace readiness"],
    depth: "quick",
    hook: "Earn & spend coins",
  },
  {
    id: "lightning-quiz",
    title: "Lightning Quiz",
    description:
      "60-second blitz across math, science, geography, and careers. Streak bonuses reward speed and accuracy.",
    subjects: ["mixed", "math", "science", "careers", "geography"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "1–2 min",
    skills: ["Speed", "Recall", "Competition"],
    depth: "quick",
    hook: "Beat the clock",
  },
  {
    id: "fact-or-fiction",
    title: "Fact or Fiction",
    description:
      "Quick true-or-false rounds on science, careers, and the world. Instant explanations turn guesses into learning.",
    subjects: ["mixed", "science", "careers"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "3–5 min",
    skills: ["Critical thinking", "Science literacy", "Curiosity"],
    depth: "quick",
    hook: "True or false challenge",
  },
  {
    id: "step-sorter",
    title: "Step Sorter",
    description:
      "Reorder shuffled steps into the correct sequence — photosynthesis, the scientific method, job hunting, and more.",
    subjects: ["science", "careers", "logic"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "4–8 min",
    skills: ["Process thinking", "Sequencing", "Career readiness"],
    depth: "quick",
    hook: "Put steps in order",
  },
  {
    id: "math-sprint",
    title: "Math Sprint",
    description:
      "Race the clock with addition, subtraction, multiplication, and division.",
    subjects: ["math"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "1–3 min",
    skills: ["Mental math", "Speed", "Number sense"],
    depth: "quick",
    hook: "60-second math rush",
  },
  {
    id: "word-scramble",
    title: "Word Scramble",
    description:
      "Unscramble academic vocabulary and unlock a quick fact about each word.",
    subjects: ["vocabulary", "mixed"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "2–5 min",
    skills: ["Spelling", "Vocabulary", "Reading"],
    depth: "quick",
    hook: "Unscramble and learn",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description:
      "Flip cards to pair terms with definitions.",
    subjects: ["mixed", "science", "careers", "math"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "3–6 min",
    skills: ["Memory", "Definitions", "Recall"],
    depth: "quick",
    hook: "Classic concentration",
  },
  {
    id: "career-sorter",
    title: "Career Sorter",
    description:
      "Sort real jobs into Holland RIASEC career types.",
    subjects: ["careers"],
    ages: ["teens", "adults", "all"],
    duration: "4–8 min",
    skills: ["Career exploration", "Self-awareness", "Job families"],
    depth: "quick",
    hook: "Match jobs to types",
  },
  {
    id: "science-trivia",
    title: "Science Trivia",
    description:
      "Multiple-choice science questions with instant explanations.",
    subjects: ["science"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "2–4 min",
    skills: ["Science literacy", "Reasoning", "Curiosity"],
    depth: "quick",
    hook: "Quick science rounds",
  },
  {
    id: "geography-capitals",
    title: "Capital Challenge",
    description:
      "Match world capitals to their countries.",
    subjects: ["geography"],
    ages: ["kids", "teens", "adults", "all"],
    duration: "3–5 min",
    skills: ["Geography", "World knowledge", "Memory"],
    depth: "quick",
    hook: "World capitals quiz",
  },
];

export function getGameById(id: string): BuiltInGame | undefined {
  return BUILT_IN_GAMES.find((g) => g.id === id);
}
